spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/careernavigator?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        static-path-pattern:   /static/**
    fox:
        swagger:
            enabled: true
    ai:
        openai:

            base-url: https://api.moonshot.cn/
            api-key: sk-aSkoBz84k3jXjcRmBDY5RHOeOYPSBI8gwW2pcx0d5Wq0kniV

            chat:
                options:
                    model: moonshot-v1-8k


mybatis:
    configuration:
        map-underscore-to-camel-case: true
