spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/careernavigator?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        static-path-pattern:   /static/**
    fox:
        swagger:
            enabled: true
    ai:
        openai:

            base-url: https://openrouter.ai/api/
            api-key: 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

            chat:
                options:
                    model: qwen/qwen3-30b-a3b:free


mybatis:
    configuration:
        map-underscore-to-camel-case: true
