spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/careernavigator?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    fox:
        swagger:
            enabled: true
    ai:
        openai:
            base-url: https://api.deepseek.com
            api-key: sk-df4d693dd6c145b4882de0317c944131
            chat.options:
                model: deepseek-chat


logging:
    level:
        org.springframework.ai.chat.client.advisor: DEBUG
        org.SETrain.CareerNavigator: DEBUG

mybatis:
    configuration:
        map-underscore-to-camel-case: true

pagehelper:
    helper-dialect: mysql
    reasonable: true       # 合理化分页参数
    support-methods-arguments: true
